[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "lumache"
authors = [{name = "Rishank", email = "rkarker1@binghamton.edu"}]
dynamic = ["version", "description"]
